### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by gregorni**

### CODE REVIEW

**Comment by fabrialberio** [comment]
Thank you for your contribution! 

I just have one little nitpick about one of the translations, but nothing to worry about!

**Comment by gregorni** [comment]
> I just have one little nitpick about one of the translations, but nothing to worry about!

What is it? Should I fix it?

**Comment by fabrialberio** [comment]
> What is it? Should I fix it?

Wait, can't you see I started a review? I have little with reviews, so I might have done something wrong.

Anyways, in my previous message I was referring to the translation of "Key name" to "Name" at line 97.
I don't know much German, but isn't there a more specific way to describe the name of a key in the file?
I am pointing this out because the word "Name" is already used in the file view to describe the application name.

**Comment by gregorni** [comment]
> Wait, can't you see I started a review?

Er, no. That's weird. It actually says "No reviews" with me.

> Anyways, in my previous message I was referring to the translation of "Key name" to "Name" at line 97.

I was thinking about that a lot. It's difficult to find something and I'm also quite dissatisfied with just translating it as "Name". I'll think about it some more.

**Comment by gregorni** [comment]
Fixed it.

**Comment by fabrialberio** [comment]
Perfect. Thanks again for your work!

**Pull request merged**
